Vite migration
chemmedia/knowledgeworker-embedded-asset-api-ui pull request #1
Opened 2024-04-08 07:25 UTC by helgenlechner

@martinkutter Ich musste wegen der Bundlesize auch diese Library umstellen. Würdest du bitte QA machen und publishen, falls alles passt?

2024-04-08 11:01 UTC, martinkutter requested changes

2024-04-08 11:01 UTC, martinkutter commented on package.json
> +    "copy-fonts": "copyfiles -u 1 src/*.woff2 dist/",
Ist das noch nötig? Durch vite werden die Fonts ja geinlined.

2024-04-08 12:42 UTC, helgenlechner commented on package.json
> +    "copy-fonts": "copyfiles -u 1 src/*.woff2 dist/",
Also bei mir steht im gebundleten JS: `src: require("./hind-light-webfont.woff2")`. Sollen die Fonts geinlined werden?

2024-04-12 11:17 UTC, martinkutter approved these changes

2024-04-17 09:37 UTC, merged